### PR TITLE
Default branch rename

### PR DESCRIPTION
**Pull request by kfcampbell**
This changes the default branch from master --> main across the repository content to match the state of the repository settings. 

----

### Before the change?

* Links, Actions, and references used the "master" default branch name. 

### After the change?

* Links, Actions, and references use the "main" default branch name

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [X] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by gr2m** [comment]
You need to set release.branches in package.json in order for the automated release to work on the main branch.

I'm on my phone, check out of the repos that use main as default branch for reference

**Comment by kfcampbell** [comment]
@gr2m thanks! Is this true even if there's no `release.branches` property set [currently](https://github.com/octokit/fixtures-server/blob/main/package.json#L53-L68)?

**Comment by gr2m** [comment]
Yes, because it falls back to the default configuration which support master, but unfortunately still doesn't support `main` out of the box (which is the reason why I don't just go ahead and rename `master` to `main` in all my repositories).

But I hope we can ship support for `main` out of the box soon. When we do, I'll remove the obsolete config from the octokit repositories

For reference, this is the config we need to add

```js
  "release": {
    "branches": [
      "+([0-9]).x",
      "main",
      "next",
      {
        "name": "beta",
        "prerelease": true
      }
    ]
  },
```

**Comment by kfcampbell** [comment]
@gr2m thanks! I've made that change on this PR and will make this change on the rest of the JS PRs. I'll request your approval so you have visibility if you're not otherwise subscribed.

**Review by gr2m — APPROVED** [review]

**Pull request merged**
