### PR TITLE
feat: ES Module

### PR DESCRIPTION
**Pull request by wolfy1339**
BREAKING CHANGE: Move to ESModules instead of CommonJS

### CODE REVIEW

**Comment by wolfy1339** [comment]
@gr2m There is only one test failure left, due to `proxyquire`. That module doesn't work under ESM since `require()` doesn't exist

**Comment by gr2m** [comment]
Thanks @wolfy1339 I'll have a look

**Comment by gr2m** [comment]
I'd like to resolve https://github.com/octokit/fixtures/pull/425 first

**Comment by wolfy1339** [comment]
From what I gather, `proxyquire` is equivalent to `jest.mock()`, and the former should work with ESM.

I think moving to Jest is going to be a requirement here

**Comment by gr2m** [comment]
> I think moving to Jest is going to be a requirement here

no problem from my side

**Comment by gr2m** [comment]
I use `uvu` in github.com/octokit/octokit-next.js and some other ESM-only Node projects and really like it so far, so I did the same here

**Comment by gr2m** [comment]
ugh now the build fails due to https://github.com/vercel/pkg/issues/1254

**Comment by gr2m** [comment]
we might need to add a pre-build step with esbuild as described here:
https://github.com/vercel/pkg/issues/782#issuecomment-882063922

At this point we could as well look into Deno instead which has the single-file binary compilation built in, what do you think?

**Pull request merged**
